# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-15 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_num_workers', models.IntegerField(default=1, verbose_name='M\xednimo N\xfamero de trabajadoras')),
                ('max_num_workers', models.IntegerField(default=1, verbose_name='M\xe1ximo N\xfamero de trabajadoras')),
                ('min_income', models.IntegerField(default=1, verbose_name='Ingresos m\xednimos')),
                ('max_income', models.IntegerField(default=1, verbose_name='Ingresos m\xe1ximos')),
                ('fee', models.FloatField(verbose_name='Cuota')),
            ],
            options={
                'ordering': ['min_num_workers', 'max_num_workers', 'min_income', 'max_income'],
                'verbose_name': 'Rango de cuotas',
                'verbose_name_plural': 'Rangos de cuotas',
            },
        ),
    ]
