# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-16 19:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_signupprocess_last_update'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('tarjeta', 'Pago con tarjeta'), ('transferencia', 'Transferencia'), ('domiciliacion', 'Domiciliaci\xf3n bancaria')], max_length=30, null=True, verbose_name='Modo de pago')),
                ('amount', models.FloatField(verbose_name='Cantidad')),
                ('concept', models.TextField(blank=True, null=True, verbose_name='Concepto')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='A\xf1adido')),
                ('completed', models.BooleanField(default=False, verbose_name='Realizado')),
                ('timestamp', models.DateTimeField(null=True, verbose_name='Fecha pago')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_payments', to='accounts.Account', verbose_name='Socia')),
                ('revised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que revis\xf3')),
            ],
        ),
    ]
