# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-17 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_pendingpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpayment',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario'),
        ),
    ]
