# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-17 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_pendingpayment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpayment',
            name='reference',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, verbose_name='Referencia del pago'),
        ),
    ]
