# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-17 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sermepa', '0002_auto_20180628_1600'),
        ('payments', '0004_pendingpayment_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.DateTimeField(auto_now_add=True, verbose_name='A\xf1adido')),
                ('type', models.CharField(blank=True, choices=[('pago', 'Pago pendiente'), ('compramoneda', 'Compra de Etics')], max_length=30, null=True, verbose_name='Tipo de pago')),
                ('bank_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sermepa.SermepaResponse', verbose_name='Respuesta TPV')),
            ],
        ),
        migrations.AlterField(
            model_name='pendingpayment',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='pendingpayment',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha pago'),
        ),
        migrations.AddField(
            model_name='pendingpayment',
            name='card_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.CardPayment', verbose_name='Pago con tarjeta'),
        ),
    ]
