# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-13 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_card_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardpayment',
            options={'ordering': ['attempt'], 'verbose_name': 'Pago con tarjeta', 'verbose_name_plural': 'Pagos con tarjeta'},
        ),
        migrations.AlterModelOptions(
            name='pendingpayment',
            options={'ordering': ['added'], 'verbose_name': 'Pago pendiente', 'verbose_name_plural': 'Pagos pendientes'},
        ),
        migrations.RemoveField(
            model_name='pendingpayment',
            name='card_payment',
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_payments', to='accounts.Account', verbose_name='Socia'),
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='pending_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.PendingPayment', verbose_name='Pago pendiente'),
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='reference',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, verbose_name='Referencia del pago'),
        ),
    ]
