# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-09 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_card_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpayment',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Pago completado'),
        ),
    ]
