# -*- encoding: utf-8 -*-
# Generated by Django 2.1.12 on 2019-10-03 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_card_payment_sermepa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardpayment',
            options={'ordering': ['attempt'], 'permissions': (('mespermission_can_view_card_payments', 'Puede ver los pagos con tarjeta'),), 'verbose_name': 'Pago con tarjeta', 'verbose_name_plural': 'Pagos con tarjeta'},
        ),
        migrations.AlterModelOptions(
            name='pendingpayment',
            options={'ordering': ['added'], 'permissions': (('mespermission_can_view_payments', 'Puede ver los pagos de cada socia'), ('mespermission_can_edit_payments', 'Puede editar el estado de los pagos')), 'verbose_name': 'Pago pendiente', 'verbose_name_plural': 'Pagos pendientes'},
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='bank_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sermepa.SermepaResponse', verbose_name='Respuesta TPV'),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='pending_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.PendingPayment', verbose_name='Pago pendiente'),
        ),
        migrations.AlterField(
            model_name='pendingpayment',
            name='revised_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que revisó'),
        ),
    ]
