# Generated by Django 2.1.12 on 2020-01-14 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0023_account_opted_out_date'),
        ('payments', '0009_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_comments', to='accounts.Account')),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Comentario de cuota',
                'verbose_name_plural': 'Comentarios de cuota',
            },
        ),
    ]
