# Generated by Django 2.1.12 on 2020-01-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_feecomments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feecomments',
            options={'ordering': ['timestamp'], 'verbose_name': 'Comentario de cuota', 'verbose_name_plural': 'Comentarios de cuota'},
        ),
    ]
