# Generated by Django 2.1.12 on 2020-02-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_feecomments_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpayment',
            name='returned',
            field=models.BooleanField(default=False, verbose_name='Devuelto'),
        ),
        migrations.AddField(
            model_name='pendingpayment',
            name='returned_reason',
            field=models.CharField(blank=True, choices=[('noexiste', 'Cuenta no existe'), ('cancelada', 'Cuenta cancelada'), ('devuelto', 'Devuelto por cliente'), ('sinfondos', 'Devuelto por el banco (falta de fondos)'), ('otros', 'Otros')], max_length=30, null=True, verbose_name='Motivo de devolución'),
        ),
        migrations.AddField(
            model_name='pendingpayment',
            name='returned_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de devolución'),
        ),
    ]
