# Generated by Django 2.1.12 on 2020-02-13 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0012_payment_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='SepaBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.DateTimeField(auto_now_add=True, verbose_name='Añadido')),
                ('amount', models.FloatField(default=0, verbose_name='Cantidad total')),
                ('sepa_file', models.FileField(blank=True, null=True, upload_to='sepa', verbose_name='Fichero SEPA')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que generó')),
                ('payments', models.ManyToManyField(blank=True, null=True, related_name='sepa_batches', to='payments.PendingPayment', verbose_name='Pagos incluídos')),
            ],
            options={
                'verbose_name': 'Remesa SEPA',
                'verbose_name_plural': 'Remesas SEPA',
                'ordering': ['-generated_by'],
                'permissions': (('mespermission_can_manage_sepa', 'Puede gestionar remesas de pagos SEPA'),),
            },
        ),
    ]
