# Generated by Django 2.1.12 on 2020-02-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_sepabatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepabatch',
            name='title',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Nombre'),
        ),
    ]
