# Generated by Django 2.1.12 on 2020-02-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_sepabatch_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBICCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de cuenta')),
                ('bank_name', models.CharField(blank=True, max_length=180, null=True, verbose_name='Nombre del banco')),
                ('bic_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código BIC')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Código BIC',
                'verbose_name_plural': 'Códigos BIC',
            },
        ),
    ]
