# Generated by Django 2.1.12 on 2020-06-02 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_annual_feecharges'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountannualfeecharge',
            name='manually_modified',
            field=models.BooleanField(default=False, verbose_name='Modificado manualmente'),
        ),
        migrations.AlterField(
            model_name='accountannualfeecharge',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_charges', to='payments.PendingPayment'),
        ),
    ]
