# Generated by Django 2.1.12 on 2020-06-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_fee_manual_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepabatchresult',
            name='fail_reason',
            field=models.IntegerField(choices=[(1, 'La cuenta no tiene IBAN'), (2, 'Entidad desconocida'), (3, 'La transferencia no tenía una cantidad positiva'), (4, 'Falta el concepto del pago')], default=0),
        ),
    ]
