# Generated by Django 2.1.12 on 2020-06-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_sepa_failreasons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sepabatchresult',
            options={'ordering': ['order'], 'verbose_name': 'Remesa SEPA', 'verbose_name_plural': 'Remesas SEPA'},
        ),
        migrations.AddField(
            model_name='sepabatchresult',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Orden'),
        ),
    ]
