# Generated by Django 2.1.12 on 2020-11-06 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_collab_verbosenames'),
        ('payments', '0020_sepabatch_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountannualfeecharge',
            name='collab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_charges', to='accounts.EntityCollaboration'),
        ),
    ]
