# Generated by Django 2.1.12 on 2021-03-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_accountannualfeecharge_collab'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountannualfeecharge',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='accountannualfeecharge',
            name='payments',
            field=models.ManyToManyField(related_name='fee_split_charges', to='payments.PendingPayment'),
        ),
        migrations.AddField(
            model_name='accountannualfeecharge',
            name='split',
            field=models.BooleanField(default=False, verbose_name='Pago fraccionado'),
        ),
    ]
