# Generated by Django 2.1.12 on 2021-03-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_fee_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountannualfeecharge',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios'),
        ),
    ]
