# Generated by Django 2.1.12 on 2021-04-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_accountannualfeecharge_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepapaymentsbatch',
            name='invoice_prefix',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Serie facturación'),
        ),
        migrations.AddField(
            model_name='sepapaymentsbatch',
            name='invoice_start',
            field=models.IntegerField(default=1, verbose_name='Número de facturación inicio'),
        ),
    ]
