# Generated by Django 2.1.12 on 2021-04-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_sepa_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpayment',
            name='invoice_number',
            field=models.IntegerField(default=1, verbose_name='Número de facturación'),
        ),
        migrations.AddField(
            model_name='pendingpayment',
            name='invoice_prefix',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Serie facturación'),
        ),
    ]
