# Generated by Django 2.1.12 on 2021-04-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0025_payment_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpayment',
            name='invoice_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de factura'),
        ),
    ]
