# Generated by Django 2.2.28 on 2022-12-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0029_accountannualfeecharge_payments_not_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountannualfeecharge',
            name='payments',
            field=models.ManyToManyField(blank=True, related_name='fee_split_charges', to='payments.PendingPayment'),
        ),
    ]
