# Generated by Django 2.2.28 on 2024-01-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0030_accountannualfeecharge_removed_warning_manytomany'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutogeneratedAnnualFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('account_type', models.CharField(choices=[('consumidoras', 'Consumidoras'), ('proveedoras', 'Proveedoras')], max_length=30, verbose_name='Modo de pago')),
            ],
            options={
                'verbose_name': 'Cuota anual autogenerada',
                'verbose_name_plural': 'Cuotas anuales autogeneradas',
                'ordering': ['-year'],
            },
        ),
    ]
