# -*- coding: utf-8 -*-

from django.core.management.base import BaseCommand

from accounts.models import Provider
from payments.models import AccountAnnualFeeCharge, AnnualFeeCharges, PendingPayment, SepaPaymentsBatch, \
    SepaBatchResult, PROVIDERS, AutogeneratedAnnualFee

from django.core.mail import EmailMessage, send_mail
from django.template.loader import render_to_string
from weasyprint import HTML
import tempfile
from weasyprint.fonts import FontConfiguration
from django.conf import settings


class Command(BaseCommand):
    help = 'Automatically send email with attached invoice to providers with annual fee added to sepa batch'

    def add_arguments(self, parser):
        parser.add_argument('sepa_id', type=int, help='Id of SEPA batch')

    def handle(self, *args, **options):
        sepa_id = options['sepa_id']

        # send_mail(
        #     "Email prueba Mercado Social",
        #     "esprueba",
        #     settings.EMAIL_SEND_FROM,
        #     ["julio@triskelapps.com"],
        #     fail_silently=False,
        # )

        sepa = SepaPaymentsBatch.objects.get(id=sepa_id)
        if not sepa:
            self.stdout.write(self.style.ERROR("SEPA batch not found"))
            return

        font_config = FontConfiguration()

        for payment in sepa.payments.all():

            to_email = payment.contact_email

            self.stdout.write(f"Processing payment for {to_email}")

            if to_email != "julio@triskelapps.com":
                self.stdout.write(self.style.WARNING(f"Wrong test email: {to_email}"))
                continue


            invoice_code = payment.invoice_code
            filename = 'factura_{}'.format(invoice_code)
            pdf_template = 'pdf/invoice.html'
            context_params = {'payment': payment,
                              'invoice_code': invoice_code,
                              'iban': settings.SEPA_CONFIG['IBAN']}

            html_string = render_to_string(pdf_template, context_params)

            with tempfile.NamedTemporaryFile(delete=True, suffix=".pdf") as pdf_file:
                HTML(string=html_string, base_url=settings.BASESITE_URL).write_pdf(pdf_file.name, font_config=font_config)
                pdf_file.seek(0)

                self.stdout.write(f"Invoice rendered. Code: {invoice_code}")

                if settings.ENABLE_EMAIL_SENDING:

                    self.stdout.write(f"Sending email...")

                    email = EmailMessage(
                        subject="Prueba email factura",
                        body="La factura debería estar adjunta",
                        from_email=settings.EMAIL_SEND_FROM,
                        to=[to_email],
                    )

                    email.attach(f'{filename}.pdf', pdf_file.read(), 'application/pdf')

                    try:
                        response = email.send(fail_silently=False)

                        if response == 1:
                            self.stdout.write(self.style.SUCCESS("Email successfully sent."))
                        else:
                            self.stdout.write(self.style.WARNING("Email failed to send."))

                    except Exception as e:
                        self.stdout.write(self.style.ERROR(f"Error sending email: {e}"))

