# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import helpers.filesystem
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='T\xedtulo')),
            ],
            options={
                'verbose_name': 'Galer\xeda',
                'verbose_name_plural': 'Galer\xedas',
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='T\xedtulo')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=helpers.filesystem.RandomFileName('photos/'))),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.Gallery')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
    ]
