# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('mespermission_can_manage_users', 'Puede ver la lista de usuarios'), ('mespermission_can_change_passwords', 'Puede cambiar la contrase\xf1a de un usuario'), ('mespermission_can_view_user_history', 'Puede consultar el historial de un usuario'), ('mespermission_can_update_users', 'Puede modificar usuarios'), ('mespermission_can_view_user_detail', 'Puede ver los detalles de un usuario'), ('mespermission_can_create_users', 'Puede a\xf1adir usuarios')), 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
