# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('cif', models.CharField(max_length=30, unique=True, verbose_name='NIF/CIF')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Apellidos')),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tel\xe9fono de contacto')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Direcci\xf3n')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='Municipio')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia')),
                ('postalcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='C\xf3digo Postal')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de alta')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de caducidad')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_guests', to='accounts.Account', verbose_name='Invitada por')),
            ],
            options={
                'verbose_name': 'Invitada',
                'verbose_name_plural': 'Invitadas',
                'permissions': (('mespermission_can_view_guests', 'Puede ver la lista de invitadas'),),
            },
        ),
        migrations.CreateModel(
            name='GuestInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40, verbose_name='Token')),
                ('used', models.BooleanField(default=False, verbose_name='Utilizado')),
                ('single_use', models.BooleanField(default=True, verbose_name='De un solo uso')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.Account', verbose_name='Invitado por')),
            ],
            options={
                'verbose_name': 'Invitacion',
                'verbose_name_plural': 'Invitaciones',
            },
        ),
    ]
