# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_permissions'),
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyAppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_guest', models.BooleanField(default=False, verbose_name='Es invitada')),
                ('is_pushed', models.BooleanField(default=False, verbose_name='Actualizado en el servidor')),
                ('cif', models.CharField(max_length=30, verbose_name='NIF/CIF')),
                ('username', models.CharField(max_length=50, null=True, verbose_name='Nombre de usuario')),
                ('uuid', models.UUIDField(null=True, verbose_name='Identificador \xfanico')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_user', to='accounts.Account', verbose_name='Socia')),
                ('guest_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_user', to='currency.GuestAccount', verbose_name='Invitada')),
            ],
        ),
    ]
