# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-12 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_currencyappuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyappuser',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_user', to='accounts.Account', verbose_name='Socia'),
        ),
        migrations.AlterField(
            model_name='currencyappuser',
            name='guest_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_user', to='currency.GuestAccount', verbose_name='Invitada'),
        ),
    ]
