# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_nullable_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestaccount',
            name='token_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_guests', to='currency.GuestInvitation', verbose_name='Token utilizado'),
        ),
        migrations.AlterField(
            model_name='guestaccount',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_guests', to='accounts.Account', verbose_name='Invitada por'),
        ),
        migrations.AlterField(
            model_name='guestinvitation',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.Account', verbose_name='Invitado por'),
        ),
    ]
