# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-20 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_global_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestaccount',
            name='guest_reference',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=50, null=True, verbose_name='Referencia invitado'),
        ),
        migrations.AlterField(
            model_name='guestaccount',
            name='cif',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='NIF/CIF'),
        ),
    ]
