# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-20 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_guest_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyappuser',
            name='cif',
            field=models.CharField(max_length=50, verbose_name='NIF/CIF'),
        ),
    ]
