# Generated by Django 2.1.12 on 2020-01-22 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercoop', '0004_registration_autodate'),
        ('currency', '0008_ondelete_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyappuser',
            name='intercoop',
            field=models.BooleanField(default=False, verbose_name='Es socia de intercoop.'),
        ),
        migrations.AddField(
            model_name='currencyappuser',
            name='intercoop_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_user', to='intercoop.IntercoopAccount', verbose_name='Intercoop'),
        ),
    ]
