# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermepa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermepaidtpv',
            name='idtpv',
            field=models.CharField(max_length=12),
        ),
    ]
