SETTING_CATEGORY_SYSTEM = "sistema"
SETTING_CATEGORY_PAYMENTS = "payments"
SETTING_CATEGORY_ACCOUNTS = "accounts"
SETTING_CATEGORY_SIMPLE_BPM = "simple_bpm"
SETTING_CATEGORY_BALANCE = "balance"

PAYMENTS_CURRENT_FEECHARGES_YEAR = 'PAYMENTS_CURRENT_FEECHARGES_YEAR'
PAYMENTS_DEFAULT_PROVIDER_FEE = 'PAYMENTS_DEFAULT_PROVIDER_FEE'
PAYMENTS_DEFAULT_CONSUMER_FEE = 'PAYMENTS_DEFAULT_CONSUMER_FEE'
PAYMENTS_DEFAULT_PROVIDER_SOCIAL_CAPITAL = 'PAYMENTS_DEFAULT_PROVIDER_SOCIAL_CAPITAL'
PAYMENTS_DEFAULT_CONSUMER_SOCIAL_CAPITAL = 'PAYMENTS_DEFAULT_CONSUMER_SOCIAL_CAPITAL'
PAYMENTS_DEFAULT_SPECIAL_FEE = 'PAYMENTS_DEFAULT_SPECIAL_FEE'

ACCOUNTS_LAST_MEMBER_ID = 'ACCOUNTS_LAST_MEMBER_ID'
ACCOUNTS_LAST_INTERCOOP_ID = 'ACCOUNTS_LAST_INTERCOOP_ID'

BALANCE_CURRENT_YEAR = 'CURRENT_BALANCE_YEAR'
