# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-04 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('activa', 'Activa'), ('acogida', 'En proceso de acogida'), ('pagoinicial', 'Pendiente de pago inicial'), ('pagopendiente', 'Pago de cuota pendiente'), ('anulada', 'Anulada por impago'), ('baja', 'Baja')], default='activa', max_length=20, verbose_name='Estado'),
        ),
    ]
