# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-04 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_entity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de alta'),
        ),
    ]
