# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-07 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_bpm', '0006_currentprocessstep_process_step'),
        ('accounts', '0004_auto_20190104_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, verbose_name='Identificador proceso')),
                ('member_type', models.CharField(blank=True, choices=[(b'consumidora', b'Socia consumidora'), (b'colaboradora', b'Socia colaboradora'), (b'proveedora', b'Socia proveedora')], max_length=30, null=True, verbose_name='Tipo de socia')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('contact_person', models.CharField(blank=True, max_length=250, null=True, verbose_name='Persona de contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tel\xe9fono de contacto')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account', verbose_name='Datos de socia')),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simple_bpm.ProcessWorkflow', verbose_name='Seguimiento del proceso')),
            ],
        ),
    ]
