# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 17:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_signupprocess_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='bonus_percent_entity',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de bonificaci\xf3n a entidades'),
        ),
        migrations.AddField(
            model_name='entity',
            name='bonus_percent_general',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de bonificaci\xf3n general'),
        ),
        migrations.AddField(
            model_name='entity',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n'),
        ),
        migrations.AddField(
            model_name='entity',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='P\xe1gina de Facebook'),
        ),
        migrations.AddField(
            model_name='entity',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Perfil de Instagram'),
        ),
        migrations.AddField(
            model_name='entity',
            name='max_percent_payment',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='M\xe1ximo porcentaje de pago aceptado'),
        ),
        migrations.AddField(
            model_name='entity',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n corta'),
        ),
        migrations.AddField(
            model_name='entity',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Canal de Telegram'),
        ),
        migrations.AddField(
            model_name='entity',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Perfil de Twitter'),
        ),
        migrations.AddField(
            model_name='entity',
            name='webpage_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='P\xe1gina web'),
        ),
    ]
