# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-24 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_default_latlong'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pay_by_debit',
            field=models.BooleanField(default=False, verbose_name='Domiciliar la cuota'),
        ),
    ]
