# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-24 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_pay_by_debit'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='apportations',
            field=models.TextField(blank=True, verbose_name='Qu\xe9 trata de aportar vuestro proyecto a la transformaci\xf3n social'),
        ),
        migrations.AddField(
            model_name='entity',
            name='benefits_destination',
            field=models.TextField(blank=True, verbose_name='A qu\xe9 se destinan los beneficios de la entidad (si los hay)'),
        ),
        migrations.AddField(
            model_name='entity',
            name='highest_salary',
            field=models.FloatField(blank=True, null=True, verbose_name='Salario m\xe1s alto'),
        ),
        migrations.AddField(
            model_name='entity',
            name='lowest_salary',
            field=models.FloatField(blank=True, null=True, verbose_name='Salario m\xe1s bajo'),
        ),
        migrations.AddField(
            model_name='entity',
            name='networking',
            field=models.TextField(blank=True, verbose_name='Redes/organizaciones/iniciativas de transformaci\xf3n social de las que la entidad forma parte'),
        ),
        migrations.AddField(
            model_name='entity',
            name='num_workers_female_non_partners',
            field=models.IntegerField(blank=True, null=True, verbose_name='N\xfam. mujeres no socias trabajadoras'),
        ),
        migrations.AddField(
            model_name='entity',
            name='num_workers_female_partners',
            field=models.IntegerField(blank=True, null=True, verbose_name='N\xfam. mujeres socias trabajadoras'),
        ),
        migrations.AddField(
            model_name='entity',
            name='num_workers_male_non_partners',
            field=models.IntegerField(blank=True, null=True, verbose_name='N\xfam. hombres no socios trabajadores'),
        ),
        migrations.AddField(
            model_name='entity',
            name='num_workers_male_partners',
            field=models.IntegerField(blank=True, null=True, verbose_name='N\xfam. hombres socios trabajadores'),
        ),
    ]
