# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_entity_social_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'permissions': (('mespermission_can_manage_categories', 'Puede gestionar las categor\xedas'),), 'verbose_name': 'Categor\xeda', 'verbose_name_plural': 'Categor\xedas'},
        ),
        migrations.AlterModelOptions(
            name='signupprocess',
            options={'permissions': (('mespermission_can_view_signups', 'Puede ver los procesos de acogida pendientes'), ('mespermission_can_create_signups', 'Puede a\xf1adir nuevos procesos de acogida'), ('mespermission_can_comment_signups', 'Puede a\xf1adir comentarios a un proceso de acogida'), ('mespermission_can_update_signups', 'Puede actualizar el estado de un proceso de acogida')), 'verbose_name': 'Proceso de acogida', 'verbose_name_plural': 'Procesos de acogida'},
        ),
    ]
