# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-22 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_entity_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cyclos_user',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Antiguo usuario en Cyclos'),
        ),
    ]
