# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-12 10:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


def copy_current_address_to_public(apps, schema_editor):
    # We can't import the model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Entity = apps.get_model('accounts', 'entity')
    for entity in Entity.objects.all():
        if entity.address and entity.address != '':
            entity.public_address = entity.address
            entity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_account_cyclos_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumer',
            options={'verbose_name': 'Consumidora', 'verbose_name_plural': 'Consumidoras'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['name'], 'verbose_name': 'Entidad', 'verbose_name_plural': 'Entidades'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'Proveedora', 'verbose_name_plural': 'Proveedoras'},
        ),
        migrations.AddField(
            model_name='entity',
            name='public_address',
            field=models.TextField(blank=True, help_text='Direcci\xf3n que aparece en el perfil de la entidad en la app del MES', null=True, verbose_name='Direcci\xf3n p\xfablica'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='categories',
            field=models.ManyToManyField(related_name='entities', to='accounts.Category', verbose_name='Categor\xedas'),
        ),

        migrations.RunPython(copy_current_address_to_public, reverse_code=migrations.RunPython.noop),
    ]
