# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-23 13:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_public_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupprocess',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signup_process', to='accounts.Account', verbose_name='Datos de socia'),
        ),
    ]
