# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-06 13:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_signup_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='start_year',
            field=models.PositiveSmallIntegerField(blank=True, default=2019, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2019)], verbose_name='A\xf1o de inicio del proyecto'),
        ),
    ]
