# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-06 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_entity_startyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupprocess',
            name='cancelled',
            field=models.BooleanField(default=False, verbose_name='Cancelado'),
        ),
    ]
