# Generated by Django 2.1.12 on 2019-10-03 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_deletionprocess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborator',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='account',
            name='legal_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.LegalForm', verbose_name='Forma legal'),
        ),
        migrations.AlterField(
            model_name='account',
            name='member_type',
            field=models.CharField(blank=True, choices=[('consumidora', 'Socia consumidora'), ('colaboradora', 'Socia colaboradora'), ('proveedora', 'Socia proveedora')], max_length=30, null=True, verbose_name='Tipo de socia'),
        ),
        migrations.AlterField(
            model_name='deletionprocess',
            name='member_type',
            field=models.CharField(blank=True, choices=[('consumidora', 'Socia consumidora'), ('colaboradora', 'Socia colaboradora'), ('proveedora', 'Socia proveedora')], max_length=30, null=True, verbose_name='Tipo de socia'),
        ),
        migrations.AlterField(
            model_name='signupprocess',
            name='member_type',
            field=models.CharField(blank=True, choices=[('consumidora', 'Socia consumidora'), ('colaboradora', 'Socia colaboradora'), ('proveedora', 'Socia proveedora')], max_length=30, null=True, verbose_name='Tipo de socia'),
        ),
    ]
