# Generated by Django 2.1.12 on 2019-10-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_ondelete_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupprocess',
            name='newsletter_check',
            field=models.BooleanField(default=False, verbose_name='Acepta alta en listas de correo'),
        ),
    ]
