# Generated by Django 2.1.12 on 2019-11-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_signupprocess_from_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='opted_out_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de baja'),
        ),
    ]
