# Generated by Django 2.1.12 on 2020-04-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_collaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='hidden_in_catalog',
            field=models.BooleanField(default=False, help_text='No mostrar esta entidad en el catálogo de la web', verbose_name='Oculta en el catálogo'),
        ),
    ]
