# Generated by Django 2.1.12 on 2020-05-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_entity_hidden_in_catalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': (('mespermission_can_view_accounts', 'Puede ver la lista de socias'), ('mespermission_can_view_reports', 'Puede ver los informes de socias')), 'verbose_name': 'Socia', 'verbose_name_plural': 'Socias'},
        ),
        migrations.AlterModelOptions(
            name='colaborator',
            options={'ordering': ['name'], 'verbose_name': 'Entidad especial', 'verbose_name_plural': 'Entidades especiales'},
        ),
        migrations.AddField(
            model_name='account',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última actualización'),
        ),
    ]
