# Generated by Django 2.1.12 on 2020-06-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_signupprocess_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='contact_email2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto (2)'),
        ),
        migrations.AddField(
            model_name='entity',
            name='contact_phone2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono de contacto (2)'),
        ),
    ]
