# Generated by Django 2.1.12 on 2020-07-13 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_refactor_collabs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitycollaboration',
            name='collaboration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities_collab', to='accounts.Collaboration'),
        ),
        migrations.AlterField(
            model_name='entitycollaboration',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_colabs', to='accounts.Entity'),
        ),
    ]
