# Generated by Django 2.1.12 on 2021-03-17 14:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_collab_verbosenames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='start_year',
            field=models.PositiveSmallIntegerField(blank=True, default=2021, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)], verbose_name='Año de inicio del proyecto'),
        ),
        migrations.AlterField(
            model_name='entitycollaboration',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_colabs', to='accounts.Entity', verbose_name='Entidad'),
        ),
    ]
