# Generated by Django 2.2.28 on 2022-10-11 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_collab_deletecascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cif',
            field=models.CharField(max_length=30, unique=True, verbose_name='NIF/CIF/Pasaporte'),
        ),
    ]
