# Generated by Django 2.2.28 on 2022-10-13 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_entity_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': (('mespermission_can_view_accounts', 'Puede ver la lista de socias'), ('mespermission_can_view_reports', 'Puede ver los informes de socias'), ('mespermission_can_view_banking_info', 'Puede ver información bancaria')), 'verbose_name': 'Socia', 'verbose_name_plural': 'Socias'},
        ),
    ]
