# Generated by Django 2.2.28 on 2022-11-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_account_social_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcapital',
            name='paid_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Modo de pago'),
        ),
    ]
