# Generated by Django 2.2.28 on 2022-12-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_provider_max_percent_payment_100'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='report_filename',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre archivo infografía'),
        ),
    ]
