# Generated by Django 2.2.28 on 2023-01-18 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_entity_report_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialcapital',
            options={'permissions': (('mespermission_can_view_social_capital', 'Puede ver los capitales sociales'),), 'verbose_name': 'Capital social', 'verbose_name_plural': 'Capitales sociales'},
        ),
    ]
