# Generated by Django 2.2.28 on 2023-01-18 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_socialcapital_view_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='start_year',
            field=models.PositiveSmallIntegerField(blank=True, default=2023, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)], verbose_name='Año de inicio del proyecto'),
        ),
    ]
