# Generated by Django 2.2.28 on 2023-01-18 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_entity_update_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='social_capital',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.SocialCapital'),
        ),
    ]
