# Generated by Django 2.2.28 on 2023-03-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_account_social_capital_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='member_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de socia'),
        ),
    ]
