# Generated by Django 2.2.28 on 2023-11-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_account_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupprocess',
            name='reas_worker',
            field=models.TextField(blank=True, null=True, verbose_name='¿Trabajas en alguna entidad del MES-Madrid y/o REAS estatal?'),
        ),
    ]
