# Generated by Django 2.2.28 on 2024-01-04 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_add_reas_worker_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='start_year',
            field=models.PositiveSmallIntegerField(blank=True, default=2024, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)], verbose_name='Año de inicio del proyecto'),
        ),
    ]
