# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-24 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='T\xedtulo')),
            ],
            options={
                'verbose_name': 'Proceso asignado',
                'verbose_name_plural': 'Procesos asignados',
                'permissions': (('mespermission_can_manage_current_process', 'Puede gestionar los procesos asociados a cada tarea'),),
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='T\xedtulo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('member_type', models.CharField(blank=True, choices=[(b'consumidora', b'Socia consumidora'), (b'colaboradora', b'Socia colaboradora'), (b'proveedora', b'Socia proveedora')], max_length=30, null=True, verbose_name='Tipo de socia')),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
                'permissions': (('mespermission_can_manage_processes', 'Puede gestionar los procesos'),),
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='T\xedtulo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n')),
                ('fa_icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icono del paso')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='simple_bpm.Process', verbose_name='Proceso')),
            ],
            options={
                'verbose_name': 'Paso de un proceso',
                'verbose_name_plural': 'Pasos de un proceso',
            },
        ),
        migrations.CreateModel(
            name='ProcessStepTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n')),
                ('process_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='simple_bpm.ProcessStep', verbose_name='Tarea de un proceso')),
            ],
            options={
                'verbose_name': 'Tarea de un proceso',
                'verbose_name_plural': 'Tareas de un proceso',
            },
        ),
    ]
