# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-25 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_bpm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
    ]
