# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-03 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simple_bpm', '0003_processstep_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentProcessStep',
            fields=[
                ('shortname', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Nombre corto')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_bpm.Process', verbose_name='Proceso asociado')),
            ],
            options={
                'verbose_name': 'Paso asignado del proceso',
                'verbose_name_plural': 'Paso asignado del proceso',
            },
        ),
        migrations.CreateModel(
            name='ProcessWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_bpm.ProcessStep', verbose_name='Paso actual')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_bpm.Process', verbose_name='Proceso que sigue')),
            ],
            options={
                'verbose_name': 'Workflow de Proceso',
                'verbose_name_plural': 'Workflows de proceso',
            },
        ),
        migrations.CreateModel(
            name='ProcessWorkflowEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simple_bpm.ProcessStep', verbose_name='Paso del proceso')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='simple_bpm.ProcessWorkflow', verbose_name='Evento de un proceso')),
            ],
            options={
                'verbose_name': 'Evento de Proceso',
                'verbose_name_plural': 'Eventos de proceso',
            },
        ),
        migrations.CreateModel(
            name='ProcessWorkflowTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_checklist', to='simple_bpm.ProcessWorkflow', verbose_name='Evento de un proceso')),
            ],
            options={
                'verbose_name': 'Tarea completadas del proceso',
                'verbose_name_plural': 'Tareas completadas del proceso',
            },
        ),
        migrations.RemoveField(
            model_name='currentprocess',
            name='id',
        ),
        migrations.AddField(
            model_name='currentprocess',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simple_bpm.Process', verbose_name='Proceso asociado'),
        ),
        migrations.AddField(
            model_name='currentprocess',
            name='shortname',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Nombre corto'),
            preserve_default=False,
        ),
    ]
