# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-03 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_bpm', '0004_process_workflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processstep',
            options={'ordering': ['order'], 'verbose_name': 'Paso de un proceso', 'verbose_name_plural': 'Pasos de un proceso'},
        ),
        migrations.AddField(
            model_name='processworkflow',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completado'),
        ),
        migrations.AddField(
            model_name='processworkflowtask',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simple_bpm.ProcessStepTask', verbose_name='Tarea completada'),
        ),
    ]
