# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-07 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_bpm', '0005_workflow_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentprocessstep',
            name='process_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simple_bpm.ProcessStep', verbose_name='Paso del proceso'),
        ),
    ]
