# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-07 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_bpm', '0006_currentprocessstep_process_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processworkflowevent',
            name='completed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
