# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-15 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_bpm', '0009_currentstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processworkflow',
            name='current_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simple_bpm.ProcessStep', verbose_name='Paso actual'),
        ),
    ]
