# Generated by Django 2.1.12 on 2020-05-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_bpm', '0011_ondelete_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='processworkflowevent',
            name='special',
            field=models.BooleanField(default=False, verbose_name='Evento especial'),
        ),
        migrations.AddField(
            model_name='processworkflowevent',
            name='special_type',
            field=models.CharField(choices=[('completed', 'Completado'), ('cancelled', 'Cancelado')], max_length=15, null=True, verbose_name='Tipo de evento especial'),
        ),
    ]
