# Generated by Django 2.1.12 on 2020-06-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_bpm', '0012_workflow_special_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processworkflowevent',
            name='special_type',
            field=models.CharField(choices=[('completed', 'Completado'), ('cancelled', 'Cancelado'), ('restarted', 'Reiniciado')], max_length=15, null=True, verbose_name='Tipo de evento especial'),
        ),
    ]
