# Generated by Django 2.1.12 on 2019-12-17 00:51

from django.db import migrations, models
import django.db.models.deletion
import helpers.filesystem
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntercoopAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('cif', models.CharField(max_length=30, unique=True, verbose_name='NIF/CIF')),
                ('first_name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=250, verbose_name='Apellidos')),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono de contacto')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='Municipio')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia')),
                ('postalcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de alta')),
                ('validated', models.BooleanField(default=False, verbose_name='Validada')),
                ('newsletter_check', models.BooleanField(default=False, verbose_name='Acepta alta en listas de correo')),
            ],
            options={
                'verbose_name': 'Socia intercooperación',
                'verbose_name_plural': 'Socias intercooperación',
            },
        ),
        migrations.CreateModel(
            name='IntercoopEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('expiration', models.IntegerField(default=3, verbose_name='Años de validez')),
                ('include_code', models.BooleanField(default=True, verbose_name='Incluir identificador de socia externa para validación')),
                ('code_label', models.CharField(blank=True, max_length=200, null=True, verbose_name='Etiqueta del identificador')),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=helpers.filesystem.RandomFileName('intercoop/'), verbose_name='Logo en alta resolución')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Entidad de intercooperación',
                'verbose_name_plural': 'Entidades de intercooperación',
            },
        ),
        migrations.AddField(
            model_name='intercoopaccount',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='intercoop.IntercoopEntity', verbose_name='Entidad asociada'),
        ),
    ]
