# Generated by Django 2.1.12 on 2019-12-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercoop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercoopentity',
            name='slug',
            field=models.CharField(blank=True, help_text='Identificador para el enlace de alta', max_length=200, null=True, verbose_name='Enlace permanente'),
        ),
    ]
