# Generated by Django 2.1.12 on 2020-01-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercoop', '0004_registration_autodate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intercoopaccount',
            options={'permissions': (('mespermission_can_add_account', 'Puede añadir socias de intercooperación'), ('mespermission_can_validate_account', 'Puede validar socias de intercooperación')), 'verbose_name': 'Socia intercooperación', 'verbose_name_plural': 'Socias intercooperación'},
        ),
        migrations.AlterModelOptions(
            name='intercoopentity',
            options={'ordering': ('name',), 'permissions': (('mespermission_can_manage_entity', 'Puede gestionar entidades de intercooperación'), ('mespermission_can_add_entity', 'Puede añadir entidades de intercooperación')), 'verbose_name': 'Entidad de intercooperación', 'verbose_name_plural': 'Entidades de intercooperación'},
        ),
    ]
