# Generated by Django 2.1.12 on 2020-05-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercoop', '0005_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercoopaccount',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última actualización'),
        ),
    ]
