# Generated by Django 2.1.12 on 2020-06-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercoop', '0006_intercoopaccount_last_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intercoopaccount',
            options={'permissions': (('mespermission_can_view_accounts', 'Puede ver las socias de intercooperación'), ('mespermission_can_add_account', 'Puede añadir socias de intercooperación'), ('mespermission_can_validate_account', 'Puede validar socias de intercooperación')), 'verbose_name': 'Socia intercooperación', 'verbose_name_plural': 'Socias intercooperación'},
        ),
    ]
