# Generated by Django 2.2.28 on 2023-03-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercoop', '0008_intercoopaccount_referral_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercoopaccount',
            name='member_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de socia'),
        ),
    ]
