# Generated by Django 2.2.28 on 2024-06-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingProperties',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, choices=[('sistema', 'Sistema'), ('payments', 'Pagos'), ('accounts', 'Socias'), ('simple_bpm', 'Procesos'), ('balance', 'Balance social')], default='sistema', max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('str_value', models.CharField(blank=True, max_length=200, null=True)),
                ('int_value', models.IntegerField(blank=True, null=True)),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('float_value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
                'ordering': ['category', 'key'],
            },
        ),
    ]
