# Generated by Django 2.1.12 on 2019-10-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_balance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialBalanceBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(default=2019, verbose_name='Año')),
                ('layout_json', models.TextField(blank=True, null=True, verbose_name='JSON de configuración de layout')),
            ],
        ),
    ]
