# Generated by Django 2.1.12 on 2019-10-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_balance', '0002_socialbalancebadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitysocialbalance',
            name='achievement',
            field=models.TextField(blank=True, null=True, verbose_name='Logro'),
        ),
        migrations.AddField(
            model_name='entitysocialbalance',
            name='challenge',
            field=models.TextField(blank=True, null=True, verbose_name='Reto'),
        ),
    ]
