# Generated by Django 2.1.12 on 2020-01-22 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_balance', '0007_entitysocialbalance_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entitysocialbalance',
            options={'permissions': (('mespermission_can_view_social_balances', 'Puede gestionar los balances sociales'), ('mespermission_can_edit_social_balances', 'Puede editar los informes de balance social')), 'verbose_name': 'Informe de balance social', 'verbose_name_plural': 'Informes de balance social'},
        ),
        migrations.AlterModelOptions(
            name='socialbalancebadge',
            options={'permissions': (('mespermission_can_view_social_badges', 'Puede ver las plantillas de sellos de balance social'), ('mespermission_can_create_social_badges', 'Puede crear plantillas de sellos de balance social')), 'verbose_name': 'Sello de balance social', 'verbose_name_plural': 'Sellos de balance social'},
        ),
    ]
