# Generated by Django 2.1.12 on 2020-06-10 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simple_bpm', '0013_process_events'),
        ('accounts', '0027_signupprocess_reference'),
        ('social_balance', '0008_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, verbose_name='Identificador proceso')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('member_type', models.CharField(blank=True, choices=[('consumidora', 'Socia consumidora'), ('colaboradora', 'Socia colaboradora'), ('proveedora', 'Socia proveedora')], max_length=30, null=True, verbose_name='Tipo de socia')),
                ('cancelled', models.BooleanField(default=False, verbose_name='Cancelado')),
                ('year', models.SmallIntegerField(default=2019, verbose_name='Año')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_process', to='accounts.Account', verbose_name='Datos de socia')),
                ('sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_sponsors', to=settings.AUTH_USER_MODEL, verbose_name='Madrina')),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simple_bpm.ProcessWorkflow', verbose_name='Seguimiento del proceso')),
            ],
            options={
                'verbose_name': 'Proceso de balance social',
                'verbose_name_plural': 'Procesos de balance social',
                'permissions': (('mespermission_can_manage_balance_process', 'Puede gestionar los procesos de balance social'), ('mespermission_can_add_balance_comments', 'Puede añadir comentarios a un proceso de balance social'), ('mespermission_can_view_balance_process', 'Puede ver los procesos de balance social')),
            },
        ),
    ]
