# Generated by Django 2.2.28 on 2022-10-11 16:17

from django.db import migrations, models
import social_balance.models.balance


class Migration(migrations.Migration):

    dependencies = [
        ('social_balance', '0010_balanceprocess_balance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitysocialbalance',
            name='report',
            field=models.FileField(blank=True, null=True, storage=social_balance.models.balance.OverwriteStorage(), upload_to='reports', verbose_name='Informe'),
        ),
    ]
